"$schema" = "https://starship.rs/config-schema.json"

format = """
[](surface0)\
$os\
$username\
[](fg:prev_bg bg:peach)\
$directory\
[](fg:prev_bg bg:green)\
$git_branch\
$git_commit\
$git_status\
[](fg:prev_bg bg:teal)\
$bun\
$c\
$deno\
$dotnet\
$golan\
$haskell\
$java\
$kotlin\
$nodejs\
$php\
$python\
$rust\
$zig\
[](fg:prev_bg bg:blue)\
$docker_context\
$kubernetes\
[](fg:prev_bg bg:mauve)\
$time\
$cmd_duration\
$memory_usage\
[ ](fg:prev_bg)\
$line_break$character"""

palette = "catppuccin_macchiato"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[os]
disabled = false
style = "fg:text bg:prev_bg"

[os.symbols]
Alpine = "[](fg:teal bg:prev_fg)"
Android = "[](fg:green bg:prev_fg)"
Arch = "[󰣇](fg:blue bg:prev_fg)"
Debian = "[󰣚](fg:red bg:prev_fg)"
Fedora = "[󰣛](fg:red bg:prev_fg)"
FreeBSD = "[](fg:red bg:prev_fg)"
Linux = "[󰌽](fg:text bg:prev_fg)"
Macos = "[󰀵](fg:text bg:prev_fg)"
NixOS = "[](fg:blue bg:prev_fg)"
OpenBSD = "[󰈺](fg:yellow bg:prev_fg)"
openSUSE = "[](fg:green bg:prev_fg)"
Raspbian = "[](fg:pink bg:prev_fg)"
Ubuntu = "[](fg:peach bg:prev_fg)"

[username]
show_always = true
style_user = "fg:text bg:prev_bg"
style_root = "bold fg:red bg:prev_bg"
format = "[ $user ]($style)"

[directory]
style = "fg:base bg:prev_bg"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[bun]
symbol = ""
style = "fg:base bg:prev_bg"
format = "[ $symbol( $version) ]($style)"

[c]
symbol = ""
style = "fg:base bg:prev_bg"
format = "[ $symbol( $version) ]($style)"

[deno]
symbol = ""
style = "fg:base bg:prev_bg"
format = "[ $symbol( $version) ]($style)"

[docker_context]
symbol = ""
style = "fg:base bg:prev_bg"
format = "[ $symbol( $context) ]($style)"

[dotnet]
symbol = ""
style = "fg:base bg:prev_bg"
format = "[ $symbol( $version) ]($style)"

[git_branch]
symbol = ""
style = "fg:base bg:prev_bg"
format = "[ $symbol $branch ]($style)"

[git_commit]
style = "fg:base bg:prev_bg"
format = "[($tag) ]($style)"

[git_status]
style = "fg:base bg:prev_bg"
format = "[($all_status$ahead_behind) ]($style)"

[golang]
symbol = ""
style = "fg:base bg:prev_bg"
format = "[ $symbol( $version) ]($style)"

[haskell]
symbol = ""
style = "fg:base bg:prev_bg"
format = "[ $symbol( $version) ]($style)"

[java]
symbol = ""
style = "fg:base bg:prev_bg"
format = "[ $symbol( $version) ]($style)"

[kotlin]
symbol = ""
style = "fg:base bg:prev_bg"
format = "[ $symbol( $version) ]($style)"

[kubernetes]
disabled = false
symbol = "󱃾"
style = "fg:base bg:prev_bg"
format = "[ $symbol( $context) ]($style)"

[nodejs]
symbol = ""
style = "fg:base bg:prev_bg"
format = "[ $symbol( $version) ]($style)"

[php]
symbol = ""
style = "fg:base bg:prev_bg"
format = "[ $symbol( $version) ]($style)"

[python]
symbol = ""
style = "fg:base bg:prev_bg"
format = "[ $symbol( $version) ]($style)"

[rust]
symbol = ""
style = "fg:base bg:prev_bg"
format = "[ $symbol( $version) ]($style)"

[zig]
symbol = ""
style = "fg:base bg:prev_bg"
format = "[ $symbol( $version) ]($style)"

[time]
disabled = false
time_format = "%R"
style = "fg:base bg:prev_bg"
format = "[  $time ]($style)"

[cmd_duration]
style = "fg:prev_fg bg:prev_bg"
format = "[ $duration ]($style)"

[memory_usage]
disabled = true
symbol = "󰍛"
style = "fg:bold prev_fg bg:prev_bg"
format = "[$symbol ${ram}]($style)"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[](bold fg:green)"
error_symbol = "[](bold fg:red)"
vimcmd_symbol = "[](bold fg:green)"
vimcmd_replace_one_symbol = "[](bold fg:mauve)"
vimcmd_replace_symbol = "[](bold fg:mauve)"
vimcmd_visual_symbol = "[](bold fg:lavender)"
