# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  hostPlatform,
  inputs,
  ...
}: {
  disabledModules = ["hardware/tuxedo-drivers.nix"]; # use stable version of tuxedo-drivers
  imports = [
    "${inputs.nixpkgs-stable}/nixos/modules/hardware/tuxedo-drivers.nix" # use stable version of tuxedo-drivers
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # boot.kernelPackages = pkgs.linuxPackages_6_12;
  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/fb7d0fd5-1954-4939-94a1-a03001da23ec";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FAB3-AAAF";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault hostPlatform;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Enable Tuxedo-rs - disabled; because it causes the internal keyboard backlight to flip out...
  hardware.tuxedo-rs = {
    enable = false;
    tailor-gui.enable = false;
  };

  # Enable Keyboard and hardware I/O driver for TUXEDO Computers laptops.
  # hardware.tuxedo-drivers.enable = true; # tuxedo-control-center enables this.

  hardware.tuxedo-control-center = {
    enable = true;
    # package = inputs.tuxedo-nixos.packages.${hostPlatform}.default; # use package versions specifies in the module.
  };

  # Enable OpenGL
  hardware.graphics = {
    enable = true;
  };

  # Load nvidia driver for Xorg and Wayland
  services.xserver.videoDrivers = [
    # For offloading, `modesetting` is needed additionally,
    # otherwise the X-server will be running permanently on nvidia,
    # thus keeping the GPU always on (see `nvidia-smi`).
    "modesetting"
    "nvidia"
  ];
  # ++
  # Enable DisplayLink - https://wiki.nixos.org/wiki/Displaylink
  # ["displaylink" "modesetting"];

  # Enable DisplayLink - https://wiki.nixos.org/wiki/Displaylink
  # services.xserver.displayManager.sessionCommands = ''
  #   ${lib.getBin pkgs.xorg.xrandr}/bin/xrandr --setprovideroutputsource 2 0
  # '';

  # Enable NVIDIA GPU
  # https://wiki.nixos.org/wiki/NVIDIA
  hardware.nvidia = {
    # Modesetting is required on wayland.
    modesetting.enable = true;

    # Nvidia power management. Experimental, and can cause sleep/suspend to fail.
    # Enable this if you have graphical corruption issues or application crashes after waking
    # up from sleep. This fixes it by saving the entire VRAM memory to /tmp/ instead
    # of just the bare essentials.
    powerManagement = {
      enable = false; # disabled as even with finegrained = true it has no beneficial effect on power draw.

      # Fine-grained power management. Turns off GPU when not in use.
      # Experimental and only works on modern Nvidia GPUs (Turing or newer).
      # The GPU in this machine (RTX 4060) qualifies.
      finegrained = false;
    };

    # Use the NVidia open source kernel module (not to be confused with the
    # independent third-party "nouveau" open source driver).
    # Support is limited to the Turing and later architectures. Full list of
    # supported GPUs is at:
    # https://github.com/NVIDIA/open-gpu-kernel-modules#compatible-gpus
    # Only available from driver 515.43.04+
    # Currently alpha-quality/buggy, so false is currently the recommended setting.
    open = true;

    # Enable the Nvidia settings menu,
    # accessible via `nvidia-settings`.
    nvidiaSettings = true;

    # Optionally, you may need to select the appropriate driver version for your specific GPU.
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  # Enable Nvidia Optimus PRIME
  ## PRIME and Wayland
  ## PRIME sync and reverse sync modes are X11-only and do not work under Wayland.
  ## PRIME offload works under Wayland, but application offloading may behave differently depending on the compositor.
  hardware.nvidia.prime = {
    sync.enable = false;
    reverseSync.enable = false;

    # To determine if offload is working, run:
    # nix-shell -p mesa-demos --run "glxinfo -B"
    # nix-shell -p mesa-demos --run "nvidia-offload glxinfo -B"
    offload = {
      enable = true;
      enableOffloadCmd = true; # Start applications with "nvidia-offload" to use the dGPU.
    };

    # To understand what uses which GPU, use the commands:
    # nvidia-smi
    # nvtop
    # nvitop

    # To determine IDs, run: nix shell nixpkgs#pciutils -c lspci -D -d ::03xx
    # Before putting them into your configuration, however, they must first be reformatted
    # assuming the bus address is <domain>:<bus>:<device>.<func>, convert all numbers from hexadecimal to decimal,
    # then the formatted string is PCI:<bus>@<domain>:<device>:<func>.
    intelBusId = "PCI:0@0:2:0";
    nvidiaBusId = "PCI:1@0:0:0";
  };

  # When the hardware.nvidia.powerManagement.enable option is enabled, the driver saves video memory to /tmp by default.
  # If /tmp is backed by tmpfs (RAM) and the GPU VRAM usage exceeds the available space, the system will not resume and you will see a blank screen instead.
  # To resolve this, redirect the temporary file to a storage location with sufficient capacity (e.g., /var/tmp) using kernel parameters:
  boot.kernelParams = ["nvidia.NVreg_TemporaryFilePath=/var/tmp"];

  # Hardware specific packages installed in system profile.
  environment.systemPackages = with pkgs; [
    nvitop # An interactive NVIDIA-GPU process viewer and beyond.
  ];
}
